const meta = {
  getUniversalEmailRecoveryExecutor: "getUniversalEmailRecoveryExecutor",
  getRecoveryConfig: "getRecoveryConfig",
  getRecoveryRequest: "getRecoveryRequest",
  getPreviousRecoveryRequest: "getPreviousRecoveryRequest",
  isActivated: "isActivated",
  canStartRecoveryRequest: "canStartRecoveryRequest",
  getAllowValidatorRecoveryAction: "getAllowValidatorRecoveryAction",
  getDisallowValidatorRecoveryAction: "getDisallowValidatorRecoveryAction",
  getAllowedValidators: "getAllowedValidators",
  getAllowedSelectors: "getAllowedSelectors",
  acceptanceCommandTemplates: "acceptanceCommandTemplates",
  recoveryCommandTemplates: "recoveryCommandTemplates",
  extractRecoveredAccountFromAcceptanceCommand: "extractRecoveredAccountFromAcceptanceCommand",
  extractRecoveredAccountFromRecoveryCommand: "extractRecoveredAccountFromRecoveryCommand",
  computeAcceptanceTemplateId: "computeAcceptanceTemplateId",
  computeRecoveryTemplateId: "computeRecoveryTemplateId",
  getVerifier: "getVerifier",
  getDkim: "getDkim",
  getEmailAuthImplementation: "getEmailAuthImplementation",
  getUpdateRecoveryConfigAction: "getUpdateRecoveryConfigAction",
  getHandleAcceptanceAction: "getHandleAcceptanceAction",
  getHandleRecoveryAction: "getHandleRecoveryAction",
  getCompleteRecoveryAction: "getCompleteRecoveryAction",
  getCancelRecoveryAction: "getCancelRecoveryAction",
  getCancelExpiredRecoveryAction: "getCancelExpiredRecoveryAction",
  computeEmailAuthAddress: "computeEmailAuthAddress",
  getGuardianConfig: "getGuardianConfig",
  getGuardian: "getGuardian",
  getAllGuardians: "getAllGuardians",
  hasGuardianVoted: "hasGuardianVoted",
  getAddGuardianAction: "getAddGuardianAction",
  getRemoveGuardianAction: "getRemoveGuardianAction",
  getChangeThresholdAction: "getChangeThresholdAction",
  UNIVERSAL_EMAIL_RECOVERY_ADDRESS: "UNIVERSAL_EMAIL_RECOVERY_ADDRESS",
  MAX_VALIDATORS: "MAX_VALIDATORS",
  MAX_NUMBER_OF_GUARDIANS: "MAX_NUMBER_OF_GUARDIANS",
  MINIMUM_RECOVERY_WINDOW: "MINIMUM_RECOVERY_WINDOW",
  CANCEL_EXPIRED_RECOVERY_COOLDOWN: "CANCEL_EXPIRED_RECOVERY_COOLDOWN",
};

export default meta;
